---
title: "Plot_OG_STEPPS_Post"
author: "Finley Shinnick"
date: "2026-04-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Functions

```{r}
library(ggplot2)
library(dplyr)
library(ncdf4)
```


## Load data

```{r}
# og_stepps_post <- load("/Users/finleyjean/Documents/STEPPS-prediction-Ecology/og_STEPPS_products/lakes_stepps.RData")

mean_stepps <- nc_open("/Users/finleyjean/Documents/STEPPS-prediction-Ecology/og_STEPPS_products/2Kyrs_Comp_Mean_Level2_v1.0.nc")
```


```{r}
# pull out the x, y coordinates present in the original stepps product
x_coord <- ncvar_get(mean_stepps, "x")
y_coord <- ncvar_get(mean_stepps, "y")
time_vals <- ncvar_get(mean_stepps, "Time")

# define a cell size (24 km in this model)
cell_size <- 24000
half_cell <- cell_size / 2

# define cell grids borders
grid_cells <- expand.grid(
  x_center = x_coord,
  y_center = y_coord
) %>%
  mutate(
    x_min = x_center - half_cell,
    x_max = x_center + half_cell,
    y_min = y_center - half_cell,
    y_max = y_center + half_cell
  )

# list taka present
taxa <- c("ASH", "BEECH", "BIRCH", "ELM", "HEMLOCK", "MAPLE", "OAK",
          "OTHER.CONIFER", "OTHER.HARDWOOD", "PINE", "SPRUCE", "TAMARACK")

# give column names x and y for location of pollen
make_locs <- function(mat) {
  as.data.frame(mat) %>%
    setNames(c("x", "y"))
}

# define coordinates of lakes we want to extract stepps data from
pollen_locs <- list(
  wisc_varve = make_locs(matrix(c(
    358152.4, 1001003,
    356758.9, 1000213,
    356204.7, 1001203
  ), ncol = 2, byrow = TRUE)),
  
  wisc_nonvarve = make_locs(matrix(c(
    295730.5, 1080402,
    305160.3, 1063040,
    302421.0, 1076170,
    315188.8, 1087291
  ), ncol = 2, byrow = TRUE)),
  
  minn_nonvarve = make_locs(matrix(c(
    169181.33, 1165575,
    127450.70, 1207032,
    94360.15, 1252942
  ), ncol = 2, byrow = TRUE))
)

# assign ids to grid cells to see what each lake falls into
# give each lake location a different ID for not (will be reduced later)
assign_cell_id <- function(lakes, grid, prefix) {
  out <- lapply(seq_len(nrow(lakes)), function(i) {
    x <- lakes$x[i]
    y <- lakes$y[i]
    
    idx <- which(
      x >= grid$x_min & x < grid$x_max &
      y >= grid$y_min & y < grid$y_max
    )
    
    grid[idx, ] %>%
      mutate(lake_id = paste0(prefix, "_", i))
  })
  
  bind_rows(out)
}

# run function
lake_cells <- bind_rows(
  assign_cell_id(pollen_locs$wisc_varve, grid_cells, "wisc_varve"),
  assign_cell_id(pollen_locs$wisc_nonvarve, grid_cells, "wisc_nonvarve"),
  assign_cell_id(pollen_locs$minn_nonvarve, grid_cells, "minn")
)

# only keep discintint grid cells
grid_keep <- lake_cells %>%
  distinct(x_center, y_center, lake_id)

full_grid_keep <- grid_keep %>%
  crossing(Time = time_vals)

# extrac the proportion values for these lakes
extract_taxa <- function(t) {
  vals <- ncvar_get(mean_stepps, t)
  
  expand.grid(
    x_center = x_coord,
    y_center = y_coord,
    Time = time_vals
  ) %>%
    mutate(Proportion = as.vector(vals),
           Taxa = t) %>%
    inner_join(full_grid_keep, by = c("x_center", "y_center", "Time"))
}

proportions_all <- bind_rows(lapply(taxa, extract_taxa))

# apply the splitting function
proportions_filtered <- split(proportions_all, proportions_all$lake_id)

# if any groups of lake fall into the same grid cell (x, y) with same proportion, reduce the number of data frames
all_df <- bind_rows(proportions_filtered)
all_df_reduced <- all_df %>% 
  distinct(x_center, y_center, Time, Taxa, Proportion, .keep_all = TRUE)

# see how many unique STEPPS grid cells we have
unique(all_df_reduced$lake_id)

```

## Plot Data

```{r}
# plot for only the given lake
plot_df <- all_df_reduced %>%
  filter(lake_id == "minn_3")

# try to find order of taxa at the last time point (for legend ordering)
label_df <- plot_df %>%
  group_by(Taxa) %>%
  filter(Time == max(Time)) %>%
  ungroup() %>%
  arrange(desc(Proportion))

taxa_order <- label_df$Taxa

# assign factors to arrange legend
plot_df <- plot_df %>%
  mutate(Taxa = factor(Taxa, levels = taxa_order))

# plot STEPPS proportions over time
ggplot((plot_df),
       aes(x = -(Time * 100), y = Proportion,
           group = Taxa, color = Taxa)) +
  geom_line(linewidth = 1) +
  xlab("Years before 1950 AD") +
  ylab("Vegetation Proportion (Out of 1.0)") +
  expand_limits(x = max(-plot_df$Time) * 1.1) +
  theme_minimal() +
  labs(title = "STEPPS Original Vegetation Reconstruction") +
  theme(legend.position = "right")
```


